### ISSUE TITLE
paginate_path error

### ISSUE THREAD

**Issue by draganmarjanovic** [UQComputingSociety/website#10]
Seems the lack of '/' at the end of the paginate_path means some attempts to access blog pages fail.

**Comment by draganmarjanovic** [comment]
Fixed in [https://github.com/UQComputingSociety/website/commit/622ec9e30016a30d384f754dc304e4fa9006b9e2](https://github.com/UQComputingSociety/website/commit/622ec9e30016a30d384f754dc304e4fa9006b9e2).

**Comment by svict4** [comment]
Can't replicate

**Comment by draganmarjanovic** [comment]
@svict4 
Try these two URL's:
https://uqcs.org.au/page2
and
https://uqcs.org.au/page2/

The latter seems to work whereas the former doesn't - on all of my machines anyway. Upon inspection, the paginate buttons point to `/page2` without the trailing '/'

**Comment by svict4** [comment]
It's an SSL issue

**Comment by draganmarjanovic** [comment]
So... any idea how it can be fixed? @svict4
