### ISSUE TITLE
Update for 2018 Sponsors

### ISSUE THREAD

**Issue by CameronAavik** [UQComputingSociety/website#110]
With the new sponsors in 2018, we need to put their logos on the website. We have gone for a tiered approach to our sponsorships this year so we will need to update the design to reflect this.

We have so far:
Gold Tier: Microsoft, Redback Technologies
Silver Tier: Polymathian, Movus, Deloitte, AginicX
Bronze Tier: Google, Softwired

There are some other sponsors that are currently being organised, we will add them to this issue as they are confirmed.

**Comment by CameronAavik** [comment]
Update: Atlassian is a Gold Tier sponsor.

**Comment by nicklambourne** [comment]
<img width="893" alt="screen shot 2018-03-07 at 3 19 28 pm" src="https://user-images.githubusercontent.com/9084563/37116387-266d487e-221c-11e8-880c-ab57cd5caf0b.png">
<img width="517" alt="screen shot 2018-03-07 at 3 19 48 pm" src="https://user-images.githubusercontent.com/9084563/37116388-267e23f6-221c-11e8-9b72-44dc29c17b39.png">
