### ISSUE TITLE
Decide whether we want to keep blog posts

### ISSUE THREAD

**Issue by CameronAavik** [UQComputingSociety/website#116]
Currently if you go to our website, you will see that the last update happened in April 7, 2017. While we could write a quick article to have something more recent, we don't have any dedicate people making blog posts for the site.

Either we:
1. Scrap the blog altogether, just make it information about the club/signing up
2. Figure out a way to ensure that it stays up to date

**Comment by mitchmcdee** [comment]
I'm for ditching the blog

**Comment by CameronAavik** [comment]
![image](https://user-images.githubusercontent.com/5800980/37327203-02ef600c-26e1-11e8-8e9a-e4e058995d35.png)
If we remove the blog post section you can see all the sponsors without scrolling

**Comment by CameronAavik** [comment]
doesn't look that good though, but I'm sure a bit of padding/style could fix that

**Comment by mitchmcdee** [comment]
I'm honestly happy to put that change through asap, maybe with some @ndl or @draganmarjanovic magic sprinkled on top.

Do we keep things like hackathon and showcase?

**Comment by draganmarjanovic** [comment]
I agree, the blog has been nothing but hassle for the past few years - it's too much effort to maintain and seemingly not read by anyone. We could potentially have a few curated articles or tutorials - but this would be easy to add and would not be the core of the site (as the blog is now).

I think moving to a single page could be our best option using the links as anchors to different points in the page - and I think that would fix the issue of the front page looking a bit funny (as per your screenshot @CameronAavik ).

I personally like the showcase and feel it's decent enough size that we could keep it - maybe have it as a carousel type thingo (if we move to a separate page) or could still have it as a separate page.

The hackathon link I definitely think we should still keep (but as mentioned in the other PR) it currently points to Eventbrite - the solution here would be to temporarily remove the link or create a dummy page that just briefly explains it saying "come back later". But I think if we move to single page it'd be fine having it as a section of the page with a disable button for "Register".

**Comment by mitchmcdee** [comment]
that all sgtm

**Comment by draganmarjanovic** [comment]
I'd be cool with spearheading this - but I'm busy til next Friday, so will pick it up then unless someone else does beforehand.

**Comment by nicklambourne** [comment]
Have pushed the fix for the hackathon link and I agree with the above, no blog is better than one than one updated 11 months ago. Happy to help out with the overhaul, too. How does this impact our decision to go static or not?

**Comment by draganmarjanovic** [comment]
Personally I think the decision as to whether we should go static could be made after the above changes are made - reeval at that point. But I think it may be a good option as it would cut out a lot of bloat from the repo / make it (ideally) simpler to contribute.

**Comment by draganmarjanovic** [comment]
I have not started work on this - and do not know when or if I will. So if someone else is keen - go for it, but feel free to loop me in on any discussion / CR's. I also think it's worth splitting the action items frmo the above discussion into a few separate issues/tasks.

**Comment by draganmarjanovic** [comment]
I have removed the blog posts.
