### ISSUE TITLE
Update committee to 2019 committee

### ISSUE THREAD

**Issue by CameronAavik** [UQComputingSociety/website#117]
trm has been replaced by tomgr in the committee, https://uqcs.org.au/about should be updated to reflect this.

**Comment by lighthou** [comment]
New users for the committee for 2019 need to be added to the website

**Comment by bradleysigma** [comment]
![Photo](https://user-images.githubusercontent.com/42644678/46912482-c3762780-cfb9-11e8-90ef-4a235e60a5c7.png)

**Comment by jdcaperon** [comment]
My github DP is fine, if a higher resolution is needed I can get another one

**Comment by matthew-lake** [comment]
Uncropped version available if needed.
![image](https://user-images.githubusercontent.com/7575455/46912604-42209400-cfbd-11e8-8a0f-0f5f3e3821bd.png)

**Comment by lighthou** [comment]
![20180108_115249](https://user-images.githubusercontent.com/28082495/46912599-2d440080-cfbd-11e8-94b8-8e399624b24c.jpg)

**Comment by nicklambourne** [comment]
![me 1](https://user-images.githubusercontent.com/9084563/47074434-8b7d1780-d239-11e8-8817-9b19bee303b4.png)
