### ISSUE TITLE
SSL certs are fooked

### ISSUE THREAD

**Issue by mitchmcdee** [UQComputingSociety/website#119]
![image](https://user-images.githubusercontent.com/10495244/43367121-84899de6-938b-11e8-817a-6666f329aee8.png)

**Comment by nicklambourne** [comment]
@TRManderson are you still responsible for these?

**Comment by TRManderson** [comment]
I mean technically I'm not responsible for anything, but yes.

Got a verification failed when I tried to renew, I'm thinking it might be something DNS related but I don't have the CloudFlare login.

**Comment by mitchmcdee** [comment]
Fixed

**Comment by TRManderson** [comment]
Had to use `--preferred-challenges http-01` to get it to work
