### ISSUE TITLE
White bars + Sticky Footer

### ISSUE THREAD

**Issue by draganmarjanovic** [UQComputingSociety/website#120]
![image](https://user-images.githubusercontent.com/914767/43472827-cfae5fa8-9531-11e8-804f-f893c4ecff25.png)

not sure wtf the whitebar is up the top (only on certain screen sizes) and same with the one at the very bottom - the footer should stick to the bottom.

**Comment by tomtomau** [comment]
Happened on portrait orientation screen for me: 
![uqcs](https://user-images.githubusercontent.com/2062363/43489717-4cfd3aae-9561-11e8-90c1-0877d1fdccd9.gif)

It's something odd with the navbar, as the `<nav>` element is `position: fixed` but it's parent is not, but has a hardcoded height and margin. Flexbox on the `<body>` means this works when the page is longer than the viewport height I think.

**Comment by draganmarjanovic** [comment]
Yeah which is why we didn't have this issue when we had posts on the site expanding that white middle section.

**Comment by jdcaperon** [comment]
Not relevant to Web2.0.
