### ISSUE TITLE
Website rewrite

### ISSUE THREAD

**Issue by CameronAavik** [UQComputingSociety/website#122]
We are looking to rewrite this website in a more beginner friendly tech stack in a similar way to how we rewrote the uqcsbot. 

Currently the website is written in Jekyll which is something not taught at UQ, and a majority of UQCS members are unfamiliar with. It also requires installing ruby, and I know people who don't want to contribute to this project because of these barriers to entry.

I am suggesting that it be rewritten in plain HTML, CSS, JS.

As it stands, the website is very simple, with only [4 lines of custom javascript](https://github.com/UQComputingSociety/website/blob/723dabc747cfa4bb81ec2b2b0b34048814fef127/_includes/head.html#L44-L47) written for it, so we don't believe we need to complicate things with anything more than plain javascript such as react, angular, typescript, and others. Going with this also approach means that we do not need any build step, meaning there is a very low barrier to entry and it makes the site very easy to modify and develop.

**Comment by JosephGarrone** [comment]
I reckon we add blockchain to it somehow as well. People need to get introduced to these technologies.
-----
On the real though, 4 lines of Javascript means we don't need Typescript, so we don't need typescript or minification. Heck, surely there are at runtime Typescript to Javascript converters we could use, especially given its only converting 4 lines?

As for Sass, that's probably a fair point, definitely makes the website easier to write and use. Perhaps there may be a lightweight in-browser one that we could use? Even if its just for developer mode (i.e. allowing those without the build tools to still contribute, but have the proper Jenkins output do pre-compilation?)

**Comment by wisebaldone** [comment]
You may wanna ping tony ( @tl ) as I believe he's used it more than me but hugo is a static binary and has asset minification backed in. Also keeps the markdown as content usecase as im guessing in the future we will want to post more on the website.

**Comment by jdcaperon** [comment]
Done.
