### ISSUE TITLE
Add Blog 

### ISSUE THREAD

**Issue by mgtlake** [UQComputingSociety/website#134]
I think it would be good for us to post simple articles based on our events, because:
- visibility for prospective members
- visibility for sponsors
- make it easier to find recordings for existing members

Idea would be:
- marketing image
- text from facebook
- video from YouTube

Should be fairly quick to produce, and could fold into weekly email schedule / responsibilities.

**Comment by TRManderson** [comment]
So good of you to volunteer to write regular blog posts!

**Comment by draganmarjanovic** [comment]
@mgtlake I removed the blog posts, I agree with you, it'd be great to have it but I don't think the effort is worth it / no one was willing. See:

https://github.com/UQComputingSociety/website/issues/116

**Comment by nicklambourne** [comment]
Won't fix, closing.
