### ISSUE TITLE
Change the colour of the join button

### ISSUE THREAD

**Issue by jdcaperon** [UQComputingSociety/website#146]
The buttons on the main page aren't a uniform colour, we should make them uniform and consistent with the rest of the styling on the website.

A small task to pick up and make your first contribution.

**Comment by kentonlam** [comment]
May want to investigate customising Bulma's colours. Something like this: https://bulma.io/documentation/customize/with-sass-cli/

**Comment by jdcaperon** [comment]
@kentonlam No: 
![image](https://user-images.githubusercontent.com/30421879/74705148-f5129900-5266-11ea-90dd-ca589962f286.png)
