### ISSUE TITLE
Style Event Calendar to Match Site and Make It Responsive

### ISSUE THREAD

**Issue by nicklambourne** [UQComputingSociety/website#157]
Feeds into #144. The calendar at https://uqcs.org/events/ looks tacky and awful and isn't responsive.

Potential fixes:

- Responsiveness: [https://profromgo.com/blog/google-calendar-responsive/](https://profromgo.com/blog/google-calendar-responsive/)
- Styling: [https://feed.mikle.com/support/custom-google-calendar-widget-using-css/](https://feed.mikle.com/support/custom-google-calendar-widget-using-css/)

**Comment by kentonlam** [comment]
Calendar from #168 is good up to tablet size. Smaller than that, it looks like this. Could probably be fixed by some custom CSS.

![image](https://user-images.githubusercontent.com/39479354/77391148-baf76280-6de3-11ea-8b25-6d52aed087bc.png)

**Comment by nicklambourne** [comment]
Closed due to #169, thanks @kentonlam!
