### ISSUE TITLE
Hamburger navigation menu on mobile

### ISSUE THREAD

**Issue by LauchieHarvey** [UQComputingSociety/website#160]
Potential lingering issue from #151 . The navigation menu does not open from the about page. Seems to be working fine from the other pages. Bug is present in both Firefox and Chrome on mobile.

**Comment by nicklambourne** [comment]
Will be addressed in #156 with this:
```
        {{ "<!-- Custom JavaScript -->" | safeHTML }}
        {{ range .Site.Params.custom_js }}
        <script src="{{ . | absURL }}"></script>
        {{ end }}
```
