### ISSUE TITLE
[Community] Initialise community page

### ISSUE THREAD

**Issue by jdcaperon** [UQComputingSociety/website#162]
Create and structure a new page that describes our community. Particular focuses include our work with the external tech community, e.g. DjangoGirls, and our internal community work, e.g. Boardgame nights and BBQs.

**Comment by kumar-ish** [comment]
Completed by [https://github.com/UQComputingSociety/website/commit/7c22ae742b4ba5087b005cf6877656bb63365203](https://github.com/UQComputingSociety/website/commit/7c22ae742b4ba5087b005cf6877656bb63365203) (woops I thought I was on a different branch but I was not and pushed so it didn't open a PR xd).
