### ISSUE TITLE
Move Google Analytics to New Domain

### ISSUE THREAD

**Issue by nicklambourne** [UQComputingSociety/website#178]
The move to uqcs.org (or the new stack) appears to have broken Google Analytics for the site. Would be good to get it working again. This issue will only be solvable by committee members with access to the attached Google Account.

**Comment by jdcaperon** [comment]
It would be worth registering the domain with Firebase, it provides analytics built-in and nicely handles multi-user for people who don't have access to the UQCS google account :)
