### ISSUE TITLE
Add press kit/media kit link

### ISSUE THREAD

**Issue by lindenwells** [UQComputingSociety/website#280]
add our [design repo](https://github.com/uqcomputingsociety/design) to a link titled "media kit" or "press kit" to the footer of the website.
This would make it easier for collaborating societies to get our various versions of logos in SVG format etcetera, since they're unlikely to check our GitHub.
Inspired by my hunt for sponsor logos earlier this year, in which [TechOne](https://technologyonecorp.com/resources/media-kit) and [Atlassian](https://www.atlassian.com/company/news/press-kit) had press kits. (there are probably others but I forget now and it's not important)

**Comment by bw97** [comment]
The repo link has already been added. I think this can be closed.

**Comment by JamesDearlove** [comment]
Good catch @bw97
