### ISSUE TITLE
Post Excerpts

### ISSUE THREAD

**Issue by draganmarjanovic** [UQComputingSociety/website#34]
Post excerpting system is hackish from before and needs to be cleaned up.

**Comment by lewisjb** [comment]
Was this resolved in #54? Or, are you after an even better way?

**Comment by draganmarjanovic** [comment]
I'm not willing to call it resolved just yet - I shall play around with this one though :)

**Comment by draganmarjanovic** [comment]
Closed as blog portion has been removed. See discussion in #116 .
