### ISSUE TITLE
Add "Tips" Section

### ISSUE THREAD

**Issue by draganmarjanovic** [UQComputingSociety/website#41]
https://try.github.io/levels/1/challenges/1
https://git-scm.com/book/en/v1
https://www.atlassian.com/git/

**Comment by nickl93** [comment]
Could we call it Resources and have it sectioned by concept (e.g. version control, Python, misc)? Would be a good place to link to things like the subject guide and the cookbook, too.

**Comment by gricey432** [comment]
I think this isn't really in the scope of the site. I think a repo would be more appropriate
