### ISSUE TITLE
GitHub Webhooks for updates

### ISSUE THREAD

**Issue by draganmarjanovic** [UQComputingSociety/website#5]
It would be better if we were using GitHub webhooks to automatically update the website.

**Comment by TRManderson** [comment]
In progress

**Comment by TRManderson** [comment]
Done

**Comment by draganmarjanovic** [comment]
Doesn't seem to actually be when content is pushed to the master repo.

**Comment by draganmarjanovic** [comment]
Doesn't actually seem to be updating when content is pushed into master.

**Comment by draganmarjanovic** [comment]
All working fine just takes a while for Jekyll to build the site.
