### ISSUE TITLE
About page has quote from exec saying how good the club is

### ISSUE THREAD

**Issue by gricey432** [UQComputingSociety/website#50]
Can we get a quote on there from someone who isn't in the committee? Looks a bit weird for us to recommend ourselves like that

**Comment by nickl93** [comment]
"UQCS is life-changing for anyone even remotely technologically minded. The sense of community, the topical events and the wealth of knowledge are all incredible, not to mention the mountains of pizza. Trust me, it'll be the best value you've ever gotten out of $5." - Nick Lambourne

**Comment by draganmarjanovic** [comment]
Fixed in: https://github.com/UQComputingSociety/website/pull/80
