### ISSUE TITLE
Consistent nav bar between pages

### ISSUE THREAD

**Issue by draganmarjanovic** [UQComputingSociety/website#60]
The nav bar should be consistent between pages.

**Comment by lewisjb** [comment]
What page/s does it differ on?

**Comment by draganmarjanovic** [comment]
@lewisjb 

https://uqcs.org.au/

vs 

https://uqcs.org.au/about.html

**Comment by draganmarjanovic** [comment]
@lewisjb Apologies - I failed to clear my cache.
