### ISSUE TITLE
Investigate migration to Frozen flask.

### ISSUE THREAD

**Issue by draganmarjanovic** [UQComputingSociety/website#62]

**Comment by lewisjb** [comment]
What's wrong with Jekyll? I'm thinking it's because first years are taught Python, so it makes it more accessible; but you don't do much non-front-end code anyway.

**Comment by draganmarjanovic** [comment]
@lewisjb Nothing, I too quite like Jekyll. We discussed it in a committee meeting (if you looked at the most recent minutes) and the main reason (as you suspected) was to make it easier for first years to participate. I personally don't think it makes a huge difference but I'm cool with investigating it and moving to it (if it seems good enough) just for the sake of trying something new and the learning experience 👍

**Comment by lewisjb** [comment]
Fair enough, keeping a discussion here about pros/cons seems like a good idea.
[Minutes for those playing along at home](https://github.com/UQComputingSociety/minutes/blob/master/2017-03-08.md)

**Comment by jack775544** [comment]
Personally I am not in favour of of changing to Frozen Flask.

Where Frozen Flask is going to be more similar to people who use Python a lot it is going to be adding a large amount of complexity to the toolchain. Needing to have a separate markdown renderer doing a 2 stage build is a lot harder then typing `jekyll serve` and having the website magically appear and autoupdate.

For someone who only knows basic HTML web design, Jekyll is easy to get into, especially since we don't use the hardcore templating elements to a very large degree in the website.

**Comment by gricey432** [comment]
There was much discussion about this in slack and the core problem that made frozen flask be brought up is that it's hard to jump in and edit the website. The point of frozen flask would be to at least have it in a language that's taught at uq.

Another solution would be to improve the documentation on this repo. If the following things were covered I think it'd be much more beginner friendly:

- What the site is made in (jekyll)
- How to get jekyll
- The directory structure of the project

I also think the following changes would make it more accessible:

- Either change everything to MD or everything to html or document which should be used where
- Wrap the whole project in a folder so we can differentiate meta files like "readme" and build scripts from files that are kind of ambiguous just from the name like "manifest"
- Remove any old stuff

**Comment by draganmarjanovic** [comment]
An issue for documentation has already been opened (in light of the last committee meeting). 
See: https://github.com/UQComputingSociety/website/issues/66

I've also opened an issue to for a cleanup:
https://github.com/UQComputingSociety/website/issues/82

**Comment by draganmarjanovic** [comment]
I'm closing this issue as I consider the discussion to be over.

**Resolution:**
- Better documentation of current setup
- Cleanup of old files and directories
- Not moving to Frozen Flask at this point in time.
