### ISSUE TITLE
Overuse of logo in mobile view

### ISSUE THREAD

**Issue by draganmarjanovic** [UQComputingSociety/website#64]
This definitely does not look right, I love the logo but...

![image](https://cloud.githubusercontent.com/assets/914767/24244973/c7e7251c-100c-11e7-9707-212b948b6283.png)

**Comment by somebody1234** [comment]
This can be solved by adding the class `hide-on-med-and-down` on the larger image, I'll do this once the PR to change the large logo to svg is merged/cancelled
