### ISSUE TITLE
UQCS Logo in navbar not sharp enough

### ISSUE THREAD

**Issue by draganmarjanovic** [UQComputingSociety/website#68]
The UQCS logo in the navbar does not seem "sharp" enough.

![image](https://cloud.githubusercontent.com/assets/914767/24279240/57bd1b2e-1094-11e7-821f-63e783c22c5d.png)

**Comment by somebody1234** [comment]
The uqcs logo?

**Comment by draganmarjanovic** [comment]
@somebody1234 Yes - my bad, I should have clarified.

**Comment by somebody1234** [comment]
Would you happen to have a svg of the white on blue logo you could pastebin?
