### ISSUE TITLE
Footer should stick to bottom

### ISSUE THREAD

**Issue by draganmarjanovic** [UQComputingSociety/website#69]
The footer does not stick to the bottom of the page. It should do so.

![image](https://cloud.githubusercontent.com/assets/914767/24279252/6e537e5a-1094-11e7-895f-e5b5b10463d5.png)

**Comment by somebody1234** [comment]
I can fix it, will do asap

**Comment by draganmarjanovic** [comment]
Fixed in https://github.com/UQComputingSociety/website/pull/74.
