### ISSUE TITLE
Investigate ways to make calendar look better

### ISSUE THREAD

**Issue by draganmarjanovic** [UQComputingSociety/website#70]
This looks horrible, last I looked we didn't have much choice but we should investigate this again.

![image](https://cloud.githubusercontent.com/assets/914767/24279274/9902d308-1094-11e7-9193-42095ef4bc31.png)

**Comment by somebody1234** [comment]
We still don't have much choice but it's probably possible to write something using the Google Calendar API, hosting on a subdomain and using an iframe pointing there.

**Comment by draganmarjanovic** [comment]
Yeah, this one is kind of a hard one but I just opened an issue to make sure to investigate it once again.

**Comment by jdcaperon** [comment]
Not relevant to Web2.0, yet.
