### ISSUE TITLE
Improved showcase page

### ISSUE THREAD

**Issue by draganmarjanovic** [UQComputingSociety/website#71]
The showcase page could be improved with some front matter and perhaps a showcase "slider" at the top which features a single project in more depth.

**Comment by somebody1234** [comment]
I can try to do this, but my laptop is dead rn so later

**Comment by draganmarjanovic** [comment]
It's fine I think I'll take this one @somebody1234. Thanks for volunteering though.

**Comment by jdcaperon** [comment]
Not relevant to Web2.0, but worth noting in re-development.
