### ISSUE TITLE
Navbar is broke at this breakpoint

### ISSUE THREAD

**Issue by draganmarjanovic** [UQComputingSociety/website#75]
The navbar breaks.

![image](https://cloud.githubusercontent.com/assets/914767/24286314/609001fe-10c0-11e7-9ebf-d19914aa63f4.png)

**Comment by draganmarjanovic** [comment]
An even worse example of this can be seen here:

![image](https://cloud.githubusercontent.com/assets/914767/24286367/a3143f5e-10c0-11e7-8513-cb8ab55fa718.png)

**Comment by lewisjb** [comment]
Is this now fixed?

**Comment by gricey432** [comment]
No, getting screenshots now

**Comment by gricey432** [comment]
For 992 < width <= 1134 or so, the nav goes down, but the share icons stay. On pages other than the homepage this white nav text on the white background is basically invisible.

![stacked nav](https://cloud.githubusercontent.com/assets/1611345/24584304/e4e04674-17ac-11e7-8eaa-94d6501d9e6c.png)

**Comment by gricey432** [comment]
For small sizes, the share icons stay but the drawer icon start moving to overlap the logo
![small](https://cloud.githubusercontent.com/assets/1611345/24584312/1d552344-17ad-11e7-96d4-c344abc118b0.png)

**Comment by gricey432** [comment]
This is fixed for me I think. Can you please double check @draganmarjanovic

**Comment by draganmarjanovic** [comment]
Fixed for me aswell @gricey432. Cheers 👍
