### ISSUE TITLE
Cleaner URLs

### ISSUE THREAD

**Issue by gricey432** [UQComputingSociety/website#83]
Having `.html` at the end of our urls looks a bit outdated imo. Thoughts?

**Comment by draganmarjanovic** [comment]
👍

**Comment by Biarity** [comment]
[History API](https://developer.mozilla.org/en/docs/Web/API/History)

**Comment by CameronAavik** [comment]
I had a look into it, and it's nothing to do with a configuration, it's just modifying links such as the following to remove the `.html`

https://github.com/UQComputingSociety/website/blob/master/_includes/main_nav.html

**Comment by TRManderson** [comment]
Must only be the case for GH Pages, as doing what the SO question says has broken our links

**Comment by TRManderson** [comment]
Fixed via modified nginx config
