### ISSUE TITLE
Pagination does not work

### ISSUE THREAD

**Issue by draganmarjanovic** [UQComputingSociety/website#9]
Clicking on the pagination buttons 1,2,3,4, etc. does not take the user to the page but redirects them to https://127.0.0.1:4000/page2/. 

- Hovering over the link displays https://uqcs.org.au/page2/ which appears right, but when accessed manually also redirects to https://127.0.0.1:4000/page2/

**Comment by draganmarjanovic** [comment]
@TRManderson Any ideas? Try accessing https://uqcs.org.au/page2/ and see what happens... =/

**Comment by svict4** [comment]
The `_config.yml` file didn't include the site.url parameter. Would that be it? I've added it in anycase.

**Comment by draganmarjanovic** [comment]
I'm almost certain that site.url isn't the problem =/ as everything else seems to work correctly and there is no problems with image and stylesheet referencing. However, your changes to `_config.yml` will be pushed to the live version automatically in a minute or so, so we shall see :)

**Comment by svict4** [comment]
Appears to be working now

**Comment by draganmarjanovic** [comment]
@svict4 Can you provide a link to page 2? Doesn't seem to work for me o.O

**Comment by svict4** [comment]
Clicking on number 2 in pagination on `index.html` takes me directly to http://uqcs.org.au/page2/

**Comment by draganmarjanovic** [comment]
Just seemed to be some lag on my end. Cheers :+1:

**Comment by svict4** [comment]
Coolbeans. I think the `_config.yml` needs to be fleshed out a bit more, even if it is with default values.
c61231d39294b33e131189aa39e221d7fde0c879
